[general]
import = ["themes/noctalia.toml"]
# import = ["themes/catppuccin-mocha.toml"]

[window]
dimensions = { columns = 120, lines = 30 }

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 14
